<?php
/** @var  Magento\HelloWorld\Block\Product\ListProduct $block */
    $productCollection = $block->getProductCollection();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
?>
<div class="content-heading">
    <h2 class="title">List Product</h2>
    <p class="info">Here is what`s trending on Luma right now</p>
</div>
<div class="block widget block-products-list grid">
    <div class="block-content">
        <div class="products-grid grid">
            <ol class="product-items widget-product-grid">
                <?php foreach ($productCollection as $product) :?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                                <span class="product-image-container" style="width: 240px;">
                                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                        <img width="240" height="300" loading="lazy" class="product-image-photo" src="<?= $block->getProductImageUrl($product->getId()) ?>">
                                    </span>
                                </span>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <?= $product->getName() ?>
                                </strong>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                    </div>
                                    <div class="reviews-actions">
                                        <a class="action view" href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                                            <?= $block->getReviewCollection($product->getId())->count() ?> Reviews
                                        </a>
                                    </div>
                                </div>
                                <div class="price-box price-final_price">
                                    <span class="price">$<?= $product->getPrice() ?></span>
                                </div>
                            </div>
                                <form class="atc-form-custom" data-product-name="<?= $product->getName()?>" data-role="tocart-form" action="<?= $listBlock->getUrl('helloworld/cart/add', ['product_id' => $product->getId()]); ?>" method="post">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            title="Add to Cart"
                                            class="action tocart primary">
                                        <span><?= __('Add to Cart') ?></span>
                                    </button>
                                </form>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>

<!--modal-->
            <div class="add-to-cart-modal-popup" style="display: none">
                <p class="product-added" style="color: #2A6002"></p>
                <span>Name:</span>
                <span class="product-name" ></span><br>
                <span>Price:</span>
                <span class="product-price"></span>
            </div>

            <script>
                require([
                    'jquery',
                ], function ($) {
                    $('.atc-form-custom').submit(function(event){
                        event.preventDefault();
                        let self = this;
                        $.ajax({
                            url: $(self).attr('action'),
                            data: {},
                            type: 'post',
                            dataType: 'json',
                            cache: false,
                            contentType: false,
                            processData: false,

                            /** @inheritdoc */
                            success: function (res) {
                                // console.log(res.product);

                                //Popup
                                var popup = $('.add-to-cart-modal-popup').modal({
                                    modalClass: 'add-to-cart-popup',
                                    title: $.mage.__("POPUP MODAL"),
                                    buttons: [
                                        {
                                            text: 'Continue',
                                            click: function () {
                                                this.closeModal();
                                            }
                                        },
                                        {
                                            text: 'Checkout',
                                            click: function () {
                                                window.location = window.checkout.checkoutUrl
                                            }
                                        }
                                    ]
                                });
                                $('.product-added').html(res.product.name + ' has been added to cart.');
                                $('.product-name').html(res.product.name);
                                $('.product-price').html('$' + res.product.price);
                                popup.modal('openModal');

                                //reload mini cart
                                require('Magento_Customer/js/customer-data').reload();

                            },
                        });
                    });
                })
            </script>
